FROM python:3.5-alpine

RUN mkdir /python_requirements
COPY requirements.txt /python_requirements.txt
COPY docker/*.sh /usr/local/bin

# Install pure-Python, compiled, and OS package dependencies.  Use scanelf to
# uninstall any compile-time OS package dependencies and keep only the run-time
# OS package dependencies.
RUN install-deps.sh /python_requirements.txt

# `Flask-pyoidc` upstream 1.2.0+ requires a version of `oic` which is
# broken with Auth0 (Auth0 is not spec compliant). Even though `Flask-pyoidc`
# has this requirement, it will still work with the older version of `oic`.
# We force a downgrade of `oic` after installing `Flask-pyoidc` so we can keep
# working with Auth0.
COPY oic_downgrade_requirements.txt /oic_downgrade_requirements.txt
RUN pip install --no-cache -r /oic_downgrade_requirements.txt

RUN apk add --update nodejs ruby && rm -rf /var/cache/apk/*
RUN gem install sass --no-document -v 3.4.25

# Create a Dockerflow version file at the root so
# we don't map over it below.
RUN echo '{\
    "source": "https://github.com/mozilla-conduit/lando-ui",\
    "version": "0.0.0",\
    "commit": "",\
    "build": "dev"\
}' >> /version.json

ADD . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && python /app/setup.py develop
CMD ["lando-ui-dev"]
