FROM python:3.5-alpine

RUN apk add --update gcc musl-dev libffi-dev python-dev openssl-dev

RUN addgroup -g 1001 app && \
    adduser -D -u 1001 -G app -s /usr/sbin/nologin app

WORKDIR /app
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

RUN apk del gcc musl-dev libffi-dev python-dev openssl-dev

COPY . /app
RUN rm -rf /app/landoui/static/src
RUN python ./setup.py develop

# run as non priviledged user
USER app

# TODO allow ops to use this as a wsgi app
