FROM python:3.8-alpine

RUN mkdir /python_requirements
COPY requirements.txt /python_requirements.txt
COPY docker/*.sh /usr/local/bin

# Install pure-Python, compiled, and OS package dependencies.  Use scanelf to
# uninstall any compile-time OS package dependencies and keep only the run-time
# OS package dependencies.
RUN install-deps.sh /python_requirements.txt

# TODO: separate dev-specific packages into their own requirements file

RUN apk add --update nodejs ruby && rm -rf /var/cache/apk/*
RUN gem install sass --no-document -v 3.4.25

# Create a Dockerflow version file at the root so
# we don't map over it below.
RUN echo '{\
    "source": "https://github.com/mozilla-conduit/lando-ui",\
    "version": "0.0.0",\
    "commit": "",\
    "build": "dev"\
}' >> /version.json

ADD . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && python /app/setup.py develop
CMD ["lando-ui-dev"]
