FROM python:3.5-alpine

RUN apk add --update gcc musl-dev libffi-dev python-dev openssl-dev

RUN mkdir /python_requirements
COPY requirements/* /python_requirements/
RUN pip install --no-cache -r /python_requirements/common.txt \
    && pip install --no-cache -r /python_requirements/dev.txt

RUN apk del gcc musl-dev libffi-dev python-dev openssl-dev

RUN apk add --update nodejs ruby && rm -rf /var/cache/apk/*
RUN npm install --global eslint
RUN gem install sass --no-ri --no-rdoc

# Create a Dockerflow version file at the root so
# we don't map over it below.
RUN echo '{\
    "source": "https://github.com/mozilla-conduit/lando-ui",\
    "version": "0.0.0",\
    "commit": "",\
    "build": "dev"\
}' >> /version.json

ADD . /app
WORKDIR /app

# We install outside of the app directory to create the .egg-info in a
# location that will not be mounted over. This means /app needs to be
# added to PYTHONPATH though.
ENV PYTHONPATH /app
RUN cd / && python /app/setup.py develop
CMD ["lando-ui-dev"]
