# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM python:3.9-slim AS assets

COPY requirements.txt /requirements.txt
COPY system_requirements.txt /system_requirements.txt

RUN \
    apt-get update && \
    xargs apt-get install -y < /system_requirements.txt && \
    apt-get clean

RUN pip install -r /requirements.txt

COPY . /app
RUN pip install --no-cache /app
RUN gem install sass --no-document -v 3.4.25

# TODO get rid of the below.
ENV OIDC_DOMAIN=dontcare
ENV OIDC_CLIENT_ID=dontcare
ENV OIDC_CLIENT_SECRET=dontcare
ENV LANDO_API_OIDC_IDENTIFIER=dontcare
ENV FLASK_APP=/app/landoui/assets_app.py
RUN flask assets build

FROM python:3.9-slim

COPY requirements.txt /requirements.txt
COPY system_requirements.txt /system_requirements.txt

RUN \
    apt-get update && \
    xargs apt-get install -y < /system_requirements.txt && \
    apt-get clean

RUN pip install -r /requirements.txt

RUN \
    addgroup --gid 10001 app && \
    adduser --disabled-password --uid 10001 --gid 10001 --gecos "" --home /app app

COPY . /app
RUN pip install --no-cache /app

COPY --from=assets /app/landoui/static/ /app/landoui/static/

EXPOSE 9000
CMD ["/usr/local/bin/uwsgi"]

RUN chown -R app:app /app/landoui/static

# uWSGI configuration
ENV UWSGI_MODULE=landoui.wsgi:app \
	UWSGI_SOCKET=:9000 \
	UWSGI_MASTER=1 \
	UWSGI_WORKERS=2 \
	UWSGI_THREADS=8 \
    # Disable worker memory sharing optimizations.  They can cause memory leaks
    # and issues with packages like Sentry.
    # See https://discuss.newrelic.com/t/newrelic-agent-produces-system-error/43446
	UWSGI_LAZY_APPS=1 \
	UWSGI_WSGI_ENV_BEHAVIOR=holy \
    # Make uWSGI die instead of reload when it gets SIGTERM (fixed in uWSGI 2.1)
    UWSGI_DIE_ON_TERM=1 \
    # Check that the options we gave uWSGI are sane
    UWSGI_STRICT=1 \
    # Die if the application threw an exception on startup
    UWSGI_NEED_APP=1

# Run as a non-privileged user
USER app

WORKDIR /app
