# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  lando-ui:
    # Assume whatever image is being used for testing has been tagged
    # as mozilla/landoui.
    image: mozilla/landoui
    environment:
      - ENV=localdev
      - LOG_LEVEL=DEBUG
    user: root
    volumes:
      - lando_test_results:/test_results
volumes:
  database_init:
  lando_test_results:
